=== boozallen/aissemble/foundation/foundation-mda/src/main/resources/aiops-composite-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#composite",
	"title": "Composite",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}
						},
						"required": [
							"name"
						]
					},
					"description": {
						"type": "string"
					},
					"column": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"protectionPolicy": {
						"type": "string"
					},
					"ethicsPolicy": {
						"type": "string"
					},
					"driftPolicy": {
						"type": "string"
					},
					"securityPolicy": {
						"type": "string"
					}
				},
				"required": [
					"name", "type"
				]
			}
		}
	},
	"required": [
		"name", "package", "fields"
	]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/RecordWithValidation.json
{
	"name": "RecordWithValidation",
	"package": "com.boozallen.aiops.mda.pattern.record",
	"description": "Example record with fields that require validation",
	"fields": [
		{
			"name": "stringValidation",
			"type": {
				"name": "stringWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "str_v8n"
		},
		{
			"name": "integerValidation",
			"type": {
				"name": "integerWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "int_v8n"
		},
		{
			"name": "decimalValidation",
			"type": {
				"name": "decimalWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "dec_v8n"
		},
		{
			"name": "floatValidation",
			"type": {
				"name": "floatWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "float_v8n"
		},
		{
			"name": "requiredSimpleType",
			"type": {
				"name": "customType",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "simple_v8n",
			"required": true
		},
		{
			"name": "requiredComplexType",
			"type": {
				"name": "stringWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "complex_v8n",
			"required": true
		}
	]
}
