=== boozallen/aissemble/foundation/foundation-mda/src/main/resources/aiops-composite-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#composite",
	"title": "Composite",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}
						},
						"required": [
							"name"
						]
					},
					"description": {
						"type": "string"
					},
					"column": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"protectionPolicy": {
						"type": "string"
					},
					"ethicsPolicy": {
						"type": "string"
					},
					"driftPolicy": {
						"type": "string"
					},
					"securityPolicy": {
						"type": "string"
					}
				},
				"required": [
					"name", "type"
				]
			}
		}
	},
	"required": [
		"name", "package", "fields"
	]
}

=== boozallen/aissemble/test/test-mda-models/test-machine-learning-model-definition/src/main/resources/records/EventLogEntry.json
{
  "name": "EventLogEntry",
  "package": "com.boozallen.aiops.foundation.inference",
  "description": "Models an entry in a generic event log and uses Elastic Common Schema concepts",
  "fields": [
    {
      "name": "sourceIpAddress",
      "type": {
        "name": "ipAddress",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": false
    },
    {
      "name": "created",
      "type": {
        "name": "dateAsSecondsSinceEpoch",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    },
    {
      "name": "kind",
      "type": {
        "name": "eventKind",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    },
    {
      "name": "category",
      "type": {
        "name": "eventCategory",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    },
    {
      "name": "outcome",
      "type": {
        "name": "eventOutcome",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    }
  ]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/RecordWithPolicies.json
{
	"name": "RecordWithPolicies",
	"package": "com.boozallen.aiops.mda.pattern.record",
	"description": "Example record with fields that have policies",
	"fields": [
		{
			"name": "fieldWithPolicies",
			"type": {
				"name": "customType",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"driftPolicy": "fieldDriftPolicy",
		    "ethicsPolicy": "fieldEthicsPolicy",
		    "protectionPolicy": "fieldProtectionPolicy"
		},
		{
			"name": "fieldWithDictionaryTypePolicies",
			"type": {
				"name": "typeWithPolicies",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			}
		},
		{
			"name": "fieldWithDictionaryTypePoliciesOverridden",
			"type": {
				"name": "typeWithPolicies",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
		    "driftPolicy": "overriddenDriftPolicy",
		    "ethicsPolicy": "overriddenEthicsPolicy",
		    "protectionPolicy": "overriddenProtectionPolicy"
		}
	]
}

=== boozallen/aissemble/test/test-mda-models/test-machine-learning-model-definition/src/main/resources/records/AdversarialThreatPrediction.json
{
  "name": "AdversarialThreatPrediction",
  "package": "com.boozallen.aiops.foundation.inference",
  "description": "Models the results of running a regression on provided event logs to determine if they are associated with adversarial threats",
  "fields": [
    {
      "name": "score",
      "type": {
        "name": "integer",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    },
    {
      "name": "threatDetected",
      "type": {
        "name": "boolean",
        "package": "com.boozallen.aiops.foundation.inference"
      },
      "required": true
    }
  ]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/RecordWithTypeCoercionValidation.json
{
  "name": "RecordWithTypeCoercionValidation",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example record with fields that require validation",
  "fields": [
    {
      "name": "integerValidation",
      "type": {
        "name": "integerWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "floatValidation",
      "type": {
        "name": "floatWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}

=== boozallen/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/CustomRec.json
{
	"name": "CustomRec",
	"package": "com.boozallen.aiops.mda.pattern.record",
	"description": "Example custom record for Spark Java Data Delivery Patterns",
	"fields": [
		{
			"name": "customField",
			"type": {
				"name": "customType",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			}
		},
		{
			"name": "binaryField",
			"type": {
				"name": "binarydata",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			}
		}
	]
}

=== boozallen/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/RecordWithValidation.json
{
	"name": "RecordWithValidation",
	"package": "com.boozallen.aiops.mda.pattern.record",
	"description": "Example record with fields that require validation",
	"fields": [
		{
			"name": "stringValidation",
			"type": {
				"name": "stringWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "str_v8n"
		},
		{
			"name": "integerValidation",
			"type": {
				"name": "integerWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "int_v8n"
		},
		{
			"name": "longValidation",
			"type": {
				"name": "longWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "long_v8n"
		},
		{
			"name": "shortValidation",
			"type": {
				"name": "shortWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "short_v8n"
		},
		{
			"name": "decimalValidation",
			"type": {
				"name": "decimalWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "dec_v8n"
		},
		{
			"name": "doubleValidation",
			"type": {
				"name": "doubleWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "dbl_v8n"
		},
		{
			"name": "floatValidation",
			"type": {
				"name": "floatWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "float_v8n"
		},
		{
			"name": "requiredSimpleType",
			"type": {
				"name": "customType",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "simple_v8n",
			"required": true
		},
		{
			"name": "requiredComplexType",
			"type": {
				"name": "stringWithValidation",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			},
			"column": "complex_v8n",
			"required": true
		}
	]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/CustomRecord.json
{
	"name": "CustomRecord",
	"package": "com.boozallen.aiops.mda.pattern.record",
	"description": "Example custom record for Pyspark Data Delivery Patterns",
	"fields": [
		{
			"name": "customField",
			"type": {
				"name": "customType",
				"package": "com.boozallen.aiops.mda.pattern.dictionary"
			}
		}
	]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/BinaryRecord.json
{
  "name": "BinaryRecord",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example record with a binary field for Pyspark Data Delivery Patterns",
  "fields": [
    {
      "name": "binaryField",
      "type": {
        "name": "binarydata",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}
