=== boozallen/aissemble/foundation/foundation-mda/src/main/resources/aiops-pipeline-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#pipeline",
	"title": "Pipeline",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"type": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"implementation": {
					"type": "string"
				},
				"versioning": {
					"type": "object",
					"properties": {
						"enabled": {
							"type": "boolean"
						}
					}
				},
				"platforms": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							}
						}
					}
				},
				"executionHelpers": {
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"name", "implementation"
			]
		},
		"fileStores": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					}
				},
				"required": [
					"name"
				]
			}
		},
		"dataLineage": {
			"type": "boolean"
		},
		"steps": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "string"
					},
					"inbound": {
						"type": "object",
						"properties": {
							"type": {
								"type": "string"
							},
							"nativeCollectionType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							},
							"recordType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							},
							"channelType": {
								"type": "string"
							},
							"channelName": {
								"type": "string"
							}
						},
						"required": [
							"type"
						]
					},
					"outbound": {
						"type": "object",
						"properties": {
							"type": {
								"type": "string"
							},
							"nativeCollectionType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							},
							"recordType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							},
							"channelType": {
								"type": "string"
							},
							"channelName": {
								"type": "string"
							}
						},
						"required": [
							"type"
						]
					},
					"persist": {
						"type": "object",
						"properties": {
							"type": {
								"type": "string"
							},
							"mode": {
								"type": "string"
							},
							"collectionType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							},
							"recordType": {
								"type": "object",
								"properties": {
									"name": {
										"type": "string"
									},
									"package": {
										"type": "string"
									}
								},
								"required": [
									"name"
								]
							}
						},
						"required": [
							"type"
						]
					},
					"metadata": {
						"type": "object",
						"properties": {
							"enabled": {
								"type": "boolean"
							}
						}
					},
					"alerting": {
						"type": "object",
						"properties": {
							"enabled": {
								"type": "boolean"
							}
						}
					},
					"postActions": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								},
								"type": {
									"type": "string"
								},
								"modelTarget": {
									"type": "string"
								},
								"modelSource": {
									"type": "string"
								}
							},
							"required": [
								"name", "type"
							]
						}
					},
					"configuration": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"key": {
									"type": "string"
								},
								"value": {
									"type": "string"
								}
							},
							"required": [
								"key", "value"
							]
						}
					},
					"fileStores": {
						"$comment": "References to named file stores defined under pipeline",
						"type": "array",
						"items": {
							"type": "string"
						}
					},
					"modelLineage": {
						"type": "object",
						"properties": {
							"enabled": {
								"type": "boolean"
							}
						}
					}
				},
				"required": [
					"name", "type"
				]
			}
		}
	},
	"required": [
		"name", "package", "type"
	]
}

=== boozallen/aissemble/test/test-mda-models/test-data-delivery-spark-model-basic/src/main/resources/pipelines/SparkJavaDataDeliveryBasic.json
{
	"name": "SparkJavaDataDeliveryBasic",
	"package": "com.boozallen.aiops.mda.basic",
	"type": {
		"name": "data-flow",
		"implementation": "data-delivery-spark"
	},
	"dataLineage": false,
	"steps": [
		{
		  "name": "ExampleSyncStep",
		  "type": "synchronous",
		  "alerting": {
			"enabled": false
		  },
		  "provenance": {
			"enabled": false
		  },
		  "dataProfiling": {
			"enabled": false
		  }
		},
		{
		  "name": "ExampleAsyncStep",
		  "type": "asynchronous",
		  "alerting": {
			"enabled": false
		  },
		  "provenance": {
			"enabled": false
		  },
		  "dataProfiling": {
			"enabled": false
		  }
		}
	  ]
	}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/pipelines/PysparkDataDeliveryPatterns.json
{
	"name": "PysparkDataDeliveryPatterns",
	"package": "com.boozallen.aiops.mda.pattern",
	"type": {
		"name": "data-flow",
		"implementation": "data-delivery-pyspark",
		"platforms": [
			{
				"name": "sedona"
			}
		]
	},
	"dataLineage": true,
	"fileStores": [{
		"name": "S3Test"
	}],
	"steps": [
		{
			"name": "bootstrap",
			"type": "generic"
		},
		{
			"name": "MessagingInboundAndOutboundAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "messaging",
				"channelName": "inboundChannel"
			},
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			}
		},
		{
			"name": "VoidInboundAndMessagingOutboundAsync",
			"type": "asynchronous",
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			}
		},
		{
			"name": "MessagingInboundAndVoidOutboundAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "messaging",
				"channelName": "inboundChannel"
			}
		},
		{
			"name": "NativeInboundAndMessagingOutboundAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native"
			},
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			}
		},
		{
			"name": "MessagingInboundAndOutbound",
			"type": "synchronous",
			"inbound": {
				"type": "messaging",
				"channelName": "inboundChannel"
			},
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			},
			"provenance": {
				"resource": "EnrichDataset",
				"subject": "Example Data Delivery Pipeline Enrich Step",
				"action": "Enrich"
			}
		},
		{
			"name": "VoidInboundAndMessagingOutbound",
			"type": "synchronous",
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			}
		},
		{
			"name": "MessagingInboundAndVoidOutbound",
			"type": "synchronous",
			"inbound": {
				"type": "messaging",
				"channelName": "inboundChannel"
			}
		},
		{
			"name": "NativeInboundAndMessagingOutbound",
			"type": "synchronous",
			"inbound": {
				"type": "native"
			},
			"outbound": {
				"type": "messaging",
				"channelName": "outboundChannel"
			}
		},
		{
			"name": "HivePersistence",
			"type": "synchronous",
			"persist": {
				"type": "hive"
			}
		},
		{
			"name": "HivePersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "hive"
			}
		},
		{
			"name": "DeltaLakePersistence",
			"type": "synchronous",
			"persist": {
				"type": "delta-lake"
			}
		},
		{
			"name": "DeltaLakePersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "delta-lake"
			}
		},
		{
			"name": "PostgresPersistence",
			"type": "synchronous",
			"persist": {
				"type": "postgres"
			}
		},
		{
			"name": "RDBMSPersistence",
			"type": "synchronous",
			"persist": {
				"type": "rdbms"
			}
		},
		{
			"name": "RDBMSPersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "rdbms"
			}
		},
		{
			"name": "PostgresPersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "postgres"
			}
		},
		{
			"name": "ElasticsearchPersistence",
			"type": "synchronous",
			"persist": {
				"type": "elasticsearch"
			}
		},
		{
			"name": "ElasticsearchPersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "elasticsearch"
			}
		},
		{
			"name": "Neo4jPersistence",
			"type": "synchronous",
			"persist": {
				"type": "neo4j"
			}
		},
		{
			"name": "Neo4jPersistenceAsync",
			"type": "asynchronous",
			"persist": {
				"type": "neo4j"
			}
		},
		{
			"name": "VoidInboundAndOutbound",
			"type": "synchronous"
		},
		{
			"name": "VoidInboundAndOutboundAsync",
			"type": "asynchronous"
		},
		{
			"name": "VoidInboundAndNativeOutbound",
			"type": "synchronous",
			"outbound": {
				"type": "native"
			}
		},
		{
			"name": "VoidInboundAndNativeOutboundAsync",
			"type": "asynchronous",
			"outbound": {
				"type": "native"
			}
		},
		{
			"name": "NativeInboundAndVoidOutbound",
			"type": "synchronous",
			"inbound": {
				"type": "native"
			}
		},
		{
			"name": "NativeInboundAndVoidOutboundAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native"
			}
		},
		{
			"name": "NativeInboundAndOutbound",
			"type": "synchronous",
			"inbound": {
				"type": "native"
			},
			"outbound": {
				"type": "native"
			}
		},
		{
			"name": "NativeInboundAndOutboundAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native"
			},
			"outbound": {
				"type": "native"
			}
		},
		{
			"name": "PersistWithCustomTypes",
			"type": "synchronous",
			"persist": {
				"type": "custom",
				"collectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				},
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomTypes",
			"type": "synchronous",
			"inbound": {
				"type": "native",
				"nativeCollectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				},
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomTypesAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native",
				"nativeCollectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				},
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomCollectionType",
			"type": "synchronous",
			"inbound": {
				"type": "native",
				"nativeCollectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomCollectionTypeAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native",
				"nativeCollectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomRecordType",
			"type": "synchronous",
			"inbound": {
				"type": "native",
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		},
		{
			"name": "NativeInboundWithCustomRecordTypeAsync",
			"type": "asynchronous",
			"inbound": {
				"type": "native",
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		},
		{
			"name": "NativeOutboundWithCustomTypes",
			"type": "synchronous",
			"outbound": {
				"type": "native",
				"nativeCollectionType": {
					"name": "customCollection",
					"package": "com.boozallen.aiops.mda.pattern.dictionary"
				},
				"recordType": {
					"name": "CustomRecord",
					"package": "com.boozallen.aiops.mda.pattern.record"
				}
			}
		}
	]
}

=== boozallen/aissemble/test/test-mda-models/test-machine-learning-model-definition/src/main/resources/pipelines/ExampleMachineLearningBasePipeline.json
{
	"name": "ExampleMachineLearningBasePipeline",
	"package": "com.boozallen.aiops",
	"type": {
		"name": "machine-learning",
		"implementation": "machine-learning-mlflow",
		"versioning": {
			"enabled": false
		}
	},
	"steps": [
        {
			"name": "bootstrap",
			"type": "generic"
		},
        {
			"name": "AissembleMachineLearningTrainingBase",
			"type": "training"
		}
    ]
}

=== boozallen/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model-basic/src/aissemble_test_data_delivery_pyspark_model_basic/resources/pipelines/PysparkDataDeliveryBasic.json
{
	"name": "PysparkDataDeliveryBasic",
	"package": "com.boozallen.aiops.mda.basic",
	"type": {
		"name": "data-flow",
		"implementation": "data-delivery-pyspark"
	},
	"dataLineage": false,
	"steps": [
	  {
		"name": "ExampleSyncStep",
		"type": "synchronous",
		"alerting": {
		  "enabled": false
		},
		"provenance": {
		  "enabled": false
		},
		"dataProfiling": {
		  "enabled": false
		}
	  },
	  {
		"name": "ExampleAsyncStep",
		"type": "asynchronous",
		"alerting": {
		  "enabled": false
		},
		"provenance": {
		  "enabled": false
		},
		"dataProfiling": {
		  "enabled": false
		}
	  }
	]
  }

=== boozallen/aissemble/test/test-mda-models/test-machine-learning-model-definition/src/main/resources/pipelines/ExampleMachineLearningPipeline.json
{
	"name": "ExampleMachineLearningPipeline",
	"package": "com.boozallen.aiops",
	"type": {
		"name": "machine-learning",
		"implementation": "machine-learning-mlflow",
		"versioning": {
			"enabled": false
		}
	},
	"steps": [
		{
			"name": "bootstrap",
			"type": "generic"
		},
		{
			"name": "AissembleMachineLearningTraining",
			"type": "training",
			"inbound": {
				"type": "messaging",
				"channelName": "train"
			},
			"modelLineage": {
				"enabled": true
			},
			"postActions": [
				{
					"name": "ExampleOnnxSklearnConversion",
					"type": "model-conversion",
					"modelTarget": "onnx",
					"modelSource": "sklearn"
				},
				{
					"name": "ExampleOnnxKerasConversion",
					"type": "model-conversion",
					"modelTarget": "onnx",
					"modelSource": "keras"
				},
				{
					"name": "ExampleCustomConversion",
					"type": "model-conversion",
					"modelTarget": "custom",
					"modelSource": "foo"
				},
				{
					"name": "ExampleFreeformPostAction",
					"type": "freeform"
				}
			]
		},
		{
			"name": "AissembleMachineLearningSagemakerTraining",
			"type": "sagemaker-training"
		},
		{
			"name": "AissembleMachineLearningInference",
			"type": "inference",
			"inbound": {
				"type": "native",
				"recordType": {
					"name": "EventLogEntry",
					"package": "com.boozallen.aiops.foundation.inference"
				}
			},
			"outbound": {
				"type": "native",
				"recordType": {
					"name": "AdversarialThreatPrediction",
					"package": "com.boozallen.aiops.foundation.inference"
				}
			}
		}
	]
}
